version: '3.8'

services:
  # Goal Mate 应用 - 中国网络优化版本
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
      # 增加构建超时时间
      timeout: 1800  # 30分钟
    container_name: goal-mate-app
    restart: unless-stopped
    # 添加网络配置
    networks:
      - goal-mate-network
    environment:
      # 数据库连接
      DATABASE_URL: ${DATABASE_URL}
      
      # Next.js 配置
      NODE_ENV: production
      PORT: 3000
      
      # API Keys (需要在部署时设置)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      
    ports:
      - "3000:3000"
    # 使用优化的启动命令
    command: >
      sh -c "
        echo 'Setting npm registry to China mirror...' &&
        npm config set registry https://registry.npmmirror.com/ &&
        echo 'Initializing database schema...' &&
        npx prisma db push &&
        echo 'Starting application...' &&
        node server.js
      "
    # 添加健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # 添加资源限制
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

# 创建自定义网络
networks:
  goal-mate-network:
    driver: bridge 